serenity.project.name=Advantage Online Shopping - Screenplay BDD - Jose Alfredo Martinez Valdes
serenity.outputDirectory=target/site/serenity
serenity.requirements.dir=src/test/resources/features/advantage
serenity.test.root=features
serenity.take.screenshots=FOR_EACH_ACTION
webdriver.driver=chrome
webdriver.autodownload=true
webdriver.timeouts.implicitlywait=10000
webdriver.wait.for.timeout=30000
serenity.browser.maximized=true
chrome.switches=--start-maximized;--remote-allow-origins=*;--disable-notifications;--disable-popup-blocking
feature.file.encoding=UTF-8
