sonar.projectKey=jamartinezv2023_compras
sonar.organization=jamartinezv2023
sonar.host.url=https://sonarcloud.io
sonar.sources=src/test/java
sonar.tests=src/test/java
sonar.java.binaries=build/classes/java/test
sonar.sourceEncoding=UTF-8
